apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: k8s-node-drainer
  namespace: kube-system
spec:
  schedule: "*/5 3-9 * * *"
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: k8s-node-drainer
          restartPolicy: Never
          containers:
          - name: k8s-node-drainer
            image: logmein/k8s-node-drainer:latest
            command: [python, main.py]
            args: [
              "--notify-after=1m",
              "--evict-after=30m",
              "--cordon-nodes-after=1d",
            ]
            resources:
              limits:
                memory: 200Mi
              requests:
                cpu: 5m
                memory: 100Mi
